project:
  type: website
  output-dir: docs

website:
  title: "Titanic Logistic Regression"
  navbar:
    left:
      - href: index.qmd
        text: Projekt
      - href: logistic_regression.qmd
        text: Regresja logistyczna

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: false
    code-tools: true
    number-sections: true
    smooth-scroll: true